//! Windows Event Log security telemetry and lineage sequence analysis per README and ADR 003.

use kavach_core::EnforcementAction;
use sha2::{Digest, Sha256};
use std::collections::VecDeque;

/// Size of the rolling event sequence window for NPU Head 3 (16 events per README).
pub const EVENT_SEQUENCE_WINDOW_SIZE: usize = 16;

/// Number of features per event in the NPU Head 3 input tensor: [1, 16, 4].
pub const EVENT_FEATURES_PER_ROW: usize = 4;

/// Critical correlated Windows event identifiers monitored by Kavach.
#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CriticalEventId {
    /// Successful logon (Event 4624).
    LogonSuccess = 4624,
    /// Failed logon attempt (Event 4625).
    LogonFailure = 4625,
    /// New unauthorized Windows service installation (Event 7045).
    ServiceInstall = 7045,
    /// Service created (Event 4697).
    ServiceCreated = 4697,
    /// Audit log cleared (attacker covering tracks - Event 1102).
    AuditLogCleared = 1102,
    /// Obfuscated PowerShell ScriptBlock execution (Event 4104).
    PowerShellScriptBlock = 4104,
    /// BugCheck / BSOD indicating kernel driver exploitation (Event 1001).
    BugCheck = 1001,
}

impl CriticalEventId {
    /// Attempts to parse a raw Windows Event ID into a CriticalEventId.
    pub fn from_u32(val: u32) -> Option<Self> {
        match val {
            4624 => Some(Self::LogonSuccess),
            4625 => Some(Self::LogonFailure),
            7045 => Some(Self::ServiceInstall),
            4697 => Some(Self::ServiceCreated),
            1102 => Some(Self::AuditLogCleared),
            4104 => Some(Self::PowerShellScriptBlock),
            1001 => Some(Self::BugCheck),
            _ => None,
        }
    }

    /// Normalized category weight for NPU feature encoding (0.0..=1.0).
    pub fn severity_weight(&self) -> f32 {
        match self {
            Self::LogonSuccess => 0.1,
            Self::LogonFailure => 0.4,
            Self::PowerShellScriptBlock => 0.6,
            Self::ServiceCreated | Self::ServiceInstall => 0.8,
            Self::BugCheck => 0.9,
            Self::AuditLogCleared => 1.0,
        }
    }
}

/// A structured record representing a captured Windows security event.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SecurityEventRecord {
    pub event_id: CriticalEventId,
    pub timestamp_unix_ms: u64,
    pub process_id: u32,
    pub subject_user: String,
    pub target_resource: String,
}

/// Correlation patterns recognized across event sequences.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CorrelationPattern {
    /// Multiple failed logons followed by a successful logon on the same account.
    BruteForceCompromised {
        username: String,
        failed_count: usize,
    },
    /// Unauthorized service installation for persistence.
    PersistenceServiceInstalled { service_name: String },
    /// Audit log was cleared (defense evasion).
    AuditLogTampering,
    /// Potentially obfuscated PowerShell script execution.
    SuspiciousScriptExecution { process_id: u32 },
}

/// An anomaly alert generated by the event intelligence engine.
#[derive(Debug, Clone, PartialEq)]
pub struct EventAnomalyAlert {
    pub pattern: CorrelationPattern,
    pub timestamp_ms: u64,
    pub recommended_action: EnforcementAction,
    pub corroborating_evidence_count: u8,
    pub evidence_digest: [u8; 32],
}

/// Rolling sequence buffer and correlator for Windows security events.
#[derive(Debug, Default)]
pub struct EventSequenceTracker {
    events: VecDeque<SecurityEventRecord>,
}

impl EventSequenceTracker {
    /// Creates a new empty event sequence tracker.
    pub fn new() -> Self {
        Self {
            events: VecDeque::with_capacity(EVENT_SEQUENCE_WINDOW_SIZE),
        }
    }

    /// Records an event, maintains the 16-event rolling window, and checks for correlation patterns.
    pub fn record_event(&mut self, record: SecurityEventRecord) -> Option<EventAnomalyAlert> {
        if self.events.len() == EVENT_SEQUENCE_WINDOW_SIZE {
            self.events.pop_front();
        }
        self.events.push_back(record.clone());

        self.correlate_recent(&record)
    }

    /// Returns the number of events currently held in the window.
    pub fn len(&self) -> usize {
        self.events.len()
    }

    /// Returns true if the tracker holds no events.
    pub fn is_empty(&self) -> bool {
        self.events.is_empty()
    }

    /// Formats the rolling 16 events into the [16, 4] feature matrix for NPU Head 3.
    pub fn build_tensor_matrix(
        &self,
    ) -> [[f32; EVENT_FEATURES_PER_ROW]; EVENT_SEQUENCE_WINDOW_SIZE] {
        let mut matrix = [[0.0f32; EVENT_FEATURES_PER_ROW]; EVENT_SEQUENCE_WINDOW_SIZE];
        let n = self.events.len();

        let mut prev_ts = if n > 0 {
            self.events[0].timestamp_unix_ms
        } else {
            0
        };

        for (i, event) in self.events.iter().enumerate() {
            let dt_ms = (event.timestamp_unix_ms.saturating_sub(prev_ts) as f32).max(0.0);
            prev_ts = event.timestamp_unix_ms;

            // Feature 0: Event severity weight
            matrix[i][0] = event.event_id.severity_weight();

            // Feature 1: Normalized delta-t (0..60s -> 0.0..1.0)
            matrix[i][1] = (dt_ms / 60_000.0).clamp(0.0, 1.0);

            // Feature 2: Hash of subject user name
            let mut hasher = Sha256::new();
            hasher.update(event.subject_user.as_bytes());
            let user_hash: [u8; 32] = hasher.finalize().into();
            matrix[i][2] = (user_hash[0] as f32) / 255.0;

            // Feature 3: PID normalized
            matrix[i][3] = ((event.process_id % 65536) as f32) / 65536.0;
        }

        matrix
    }

    /// Internal correlation analyzer checking for known multi-event attack patterns.
    fn correlate_recent(&self, latest: &SecurityEventRecord) -> Option<EventAnomalyAlert> {
        let mut hasher = Sha256::new();
        hasher.update((latest.event_id as u32).to_be_bytes());
        hasher.update(latest.timestamp_unix_ms.to_be_bytes());
        hasher.update(latest.process_id.to_be_bytes());
        hasher.update(latest.subject_user.as_bytes());
        hasher.update(latest.target_resource.as_bytes());
        let evidence_digest: [u8; 32] = hasher.finalize().into();

        // 1. Audit log cleared (Event 1102) -> immediate high-priority alert
        if latest.event_id == CriticalEventId::AuditLogCleared {
            return Some(EventAnomalyAlert {
                pattern: CorrelationPattern::AuditLogTampering,
                timestamp_ms: latest.timestamp_unix_ms,
                recommended_action: EnforcementAction::Alert,
                corroborating_evidence_count: 2,
                evidence_digest,
            });
        }

        // 2. New service installation (Event 7045 or 4697) -> persistence alert
        if latest.event_id == CriticalEventId::ServiceInstall
            || latest.event_id == CriticalEventId::ServiceCreated
        {
            return Some(EventAnomalyAlert {
                pattern: CorrelationPattern::PersistenceServiceInstalled {
                    service_name: latest.target_resource.clone(),
                },
                timestamp_ms: latest.timestamp_unix_ms,
                recommended_action: EnforcementAction::Alert,
                corroborating_evidence_count: 2,
                evidence_digest,
            });
        }

        // 3. Brute force: 3+ Event 4625 (LogonFailure) followed by Event 4624 (LogonSuccess)
        if latest.event_id == CriticalEventId::LogonSuccess {
            let recent_failures = self
                .events
                .iter()
                .filter(|e| {
                    e.event_id == CriticalEventId::LogonFailure
                        && e.subject_user == latest.subject_user
                        && latest.timestamp_unix_ms.saturating_sub(e.timestamp_unix_ms) <= 60_000
                })
                .count();

            if recent_failures >= 3 {
                return Some(EventAnomalyAlert {
                    pattern: CorrelationPattern::BruteForceCompromised {
                        username: latest.subject_user.clone(),
                        failed_count: recent_failures,
                    },
                    timestamp_ms: latest.timestamp_unix_ms,
                    recommended_action: EnforcementAction::Alert,
                    corroborating_evidence_count: 3,
                    evidence_digest,
                });
            }
        }

        // 4. PowerShell ScriptBlock (Event 4104)
        if latest.event_id == CriticalEventId::PowerShellScriptBlock {
            return Some(EventAnomalyAlert {
                pattern: CorrelationPattern::SuspiciousScriptExecution {
                    process_id: latest.process_id,
                },
                timestamp_ms: latest.timestamp_unix_ms,
                recommended_action: EnforcementAction::Alert,
                corroborating_evidence_count: 1,
                evidence_digest,
            });
        }

        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_audit_log_cleared_detection() {
        let mut tracker = EventSequenceTracker::new();
        let record = SecurityEventRecord {
            event_id: CriticalEventId::AuditLogCleared,
            timestamp_unix_ms: 1_700_000_000_000,
            process_id: 1234,
            subject_user: "SYSTEM".into(),
            target_resource: "Security".into(),
        };

        let alert = tracker
            .record_event(record)
            .expect("must alert on log clear");
        assert_eq!(alert.pattern, CorrelationPattern::AuditLogTampering);
    }

    #[test]
    fn test_brute_force_followed_by_success() {
        let mut tracker = EventSequenceTracker::new();
        let base_ts = 1_700_000_000_000u64;

        // 3 failed logons
        for i in 0..3 {
            tracker.record_event(SecurityEventRecord {
                event_id: CriticalEventId::LogonFailure,
                timestamp_unix_ms: base_ts + (i * 1000),
                process_id: 600,
                subject_user: "Administrator".into(),
                target_resource: "Workstation".into(),
            });
        }

        // Followed by logon success
        let success = SecurityEventRecord {
            event_id: CriticalEventId::LogonSuccess,
            timestamp_unix_ms: base_ts + 4000,
            process_id: 600,
            subject_user: "Administrator".into(),
            target_resource: "Workstation".into(),
        };

        let alert = tracker
            .record_event(success)
            .expect("must alert on brute force success");
        assert!(matches!(
            alert.pattern,
            CorrelationPattern::BruteForceCompromised {
                failed_count: 3,
                ..
            }
        ));
    }

    #[test]
    fn test_tensor_matrix_dimensions() {
        let mut tracker = EventSequenceTracker::new();
        for i in 0..EVENT_SEQUENCE_WINDOW_SIZE {
            tracker.record_event(SecurityEventRecord {
                event_id: CriticalEventId::LogonSuccess,
                timestamp_unix_ms: 1_000_000 + (i as u64 * 1000),
                process_id: 1000 + i as u32,
                subject_user: "testuser".into(),
                target_resource: "domain".into(),
            });
        }

        let matrix = tracker.build_tensor_matrix();
        assert_eq!(matrix.len(), EVENT_SEQUENCE_WINDOW_SIZE);
        assert_eq!(matrix[0].len(), EVENT_FEATURES_PER_ROW);
    }
}
