[package]
name = "kavach-sensors"
version = "0.3.0-alpha"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
kavach-core = { path = "../kavach-core" }
kavach-tripwire = { path = "../kavach-tripwire" }
kavach-beacon = { path = "../kavach-beacon" }
kavach-events = { path = "../kavach-events" }
kavach-firewall = { path = "../kavach-firewall" }
crossbeam-channel = "0.5"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_Pipes",
    "Win32_Storage_FileSystem",
    "Win32_System_Diagnostics_Etw",
    "Win32_NetworkManagement_WindowsFilteringPlatform",
] }
